### ISSUE TITLE
An Error Message Occured during OTU Clustering Initialization

### ISSUE THREAD

**Issue by onurdogan** [TillMacher/apscale_gui#2]
Hello! 

I got an error message (Unexpected error: <class 'IndexError'>) at the begining of "OTU Clustering" step (following steps were completed: "paired-end merging, primer trimming, quality filtering, starting dereplication & pooling"), and the vSearch module was installed.  Do you have any recommendations for this situation?
Thank you for developing the program and for your time again.

Onur.

![Python - APSCALE 2023-06-04 at 2 19 06 PM](https://github.com/TillMacher/apscale_gui/assets/11692156/4163ccc7-c769-4536-9b13-7883b67e28d5)

**Comment by TillMacher** [comment]
Can you please show the error that is printed in the console when clicking "Exit"?

**Comment by onurdogan** [comment]
Hi again, here they are.
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscale_gui/__main__.py", line 880, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscale_gui/__main__.py", line 475, in main
    pe_merging_main(str(path_to_outdirs))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscale/b_pe_merging.py", line 167, in main
    Parallel(n_jobs=cores)(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
IndexError: list index out of range
onurdogan@Onurs-iMac ~ % 
```

**Comment by onurdogan** [comment]
By the way, I tried using a few files with the "...fastq.gz" extension and successfully completed all the steps. However, when I attempted to use all the files I've owned, I encountered an error during the "OTU clustering" step. I have attached the log files related to this process.

You can find log file here : 

1. [ apscale_gui_worked_then_error](https://www.dropbox.com/s/ra104evsjn70sd0/apscale_gui_worked_then_error.txt?dl=0)
2. [apscale_gui_worked](https://www.dropbox.com/s/cwn6nfissjbnqg9/apscale_gui_worked_log.txt?dl=0)

If you have time, I can demonstrate it using AnyDesk/Teamviewer at a mutually convenient time.

Best,

**Comment by onurdogan** [comment]
Just realised that I did a mistake in naming the samples as "...R1.fastq.gz" and "...R2.fastq.gz". This incorrect naming resulted in errors in my analysis. After the file was correctly named, the analysis was **[successfully](https://www.dropbox.com/s/iv8d9vq7pj6qnq3/apscale_gui-all-samples-42.txt?dl=0)** performed by the "**[All-in-One analysis](https://github.com/DominikBuchner/BOLDigger)**" module. Now, I'll be attempt the "**[NCBI Blast](https://github.com/TillMacher/apscale_gui#local-blast)**" module. Previously, "...xlsx" outputs of all of my these files in **[BOLDigger](https://github.com/DominikBuchner/BOLDigger)** I've obtained. I hope that I can be adapt these outputs for analysis using "Taxon Table Tools ([TTT](https://github.com/TillMacher/TaxonTableTools))" too.

Thank you for the development of the programs.
Onur.

**Comment by TillMacher** [comment]
Good to hear that you were able to fix the error!

Yes, the output of APSCALE and BOLDIgger is compatible with TTT! The next update will make the conversion even easier, but I don't have the time to either update APSCALE or TTT at the moment. So you will need to perform some minor manual adjustments of the tables for now.
