### ISSUE TITLE
NCBI Blast TypeError: argument of type 'float' is not iterable

### ISSUE THREAD

**Issue by MerjanK** [TillMacher/apscale_gui#9]
Hi, while i was trying to run ncbi blast in apscale, in some of the fasta subsets i keep encountering this error. I've tried to exclude uncultured sample sequences during blast search and downloaded xml2 files but i still had the same error. Has anyone had a similar issue? Could it be related with a specific OTU causing this error because it gets a hit in blastn that does not fit into the format of the program?
Thanks in advance!
Traceback (most recent call last):
  File "c:\users\marja\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\marja\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\marja\AppData\Local\Programs\Python\Python39\Scripts\apscale_gui.exe\__main__.py", line 7, in <module>
  File "c:\users\marja\appdata\local\programs\python\python39\lib\site-packages\apscale_gui\__main__.py", line 611, in main
    blast_xml_to_taxonomy(fasta_file, xml_files, read_table, limit)
  File "c:\users\marja\appdata\local\programs\python\python39\lib\site-packages\apscale_gui\blast_utilities.py", line 237, in blast_xml_to_taxonomy
    if 'uncultured' in hit[6]:
TypeError: argument of type 'float' is not iterable

**Comment by TillMacher** [comment]
Hi, I have not yet seen the particular error. I will have a look at it and try to provide a fix until end of the week.
